#!/usr/bin/env bash
set -euo pipefail

# --- 0) load .env ---
if [ -f ".env" ]; then
  # shellcheck disable=SC1091
  source .env
else
  echo "Please create db/.env from .env.example first."
  exit 1
fi

POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_USER="${POSTGRES_USER:-cc_user}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-cc_pass}"
POSTGRES_DB="${POSTGRES_DB:-witcher_cc}"

DEPLOY_FILE="sql/wcc_sql_deploy.sql"

# When deploying to RDS you often want to avoid the "container mode" autodetection,
# otherwise an active local docker-compose postgres might accidentally receive the seed.
WCC_SEED_FORCE_HOST="${WCC_SEED_FORCE_HOST:-false}"

# Useful for CI / audits: generate the merged SQL file but do not apply it.
WCC_SEED_MERGE_ONLY="${WCC_SEED_MERGE_ONLY:-false}"

# --- 0.5) setup pgadmin servers.json ---
mkdir -p pgadmin
cat > pgadmin/servers.json <<EOF
{
  "Servers": {
    "1": {
      "Name": "Witcher CC Database",
      "Group": "Servers",
      "Host": "postgres",
      "Port": 5432,
      "MaintenanceDB": "postgres",
      "Username": "${POSTGRES_USER}",
      "Password": "${POSTGRES_PASSWORD}",
      "SSLMode": "prefer",
      "Comment": "Auto-configured database connection",
      "PassFile": "",
      "BgColor": "",
      "FgColor": "",
      "Service": "",
      "Shared": false,
      "SharedUsername": "",
      "SavePassword": true
    }
  }
}
EOF
echo "[seed] generated pgadmin/servers.json with database connection settings"

echo "[seed] detected host port from .env: $POSTGRES_PORT"

# --- 1) decide how to connect ---
use_container=false
if [ "$WCC_SEED_FORCE_HOST" != "true" ] && docker compose ps postgres >/dev/null 2>&1; then
  echo "[seed] trying container mode (connecting inside container to localhost:5432)..."
  for i in {1..60}; do
    if docker compose exec -T postgres pg_isready -h localhost -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
      use_container=true
      break
    fi
    sleep 2
  done
fi

if "$use_container"; then
  echo "[seed] container mode confirmed."
else
  echo "[seed] fallback to host mode (using .env host/port: $POSTGRES_HOST:$POSTGRES_PORT)"
  for i in {1..60}; do
    if pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done
fi

# --- 2) collect SQL files ---
shopt -s nullglob
mapfile -t FILES < <(ls -1 sql/*.sql 2>/dev/null | sort)
if [ "${#FILES[@]}" -eq 0 ]; then
  echo "[seed] no SQL files in db/sql"
  rm -f "$DEPLOY_FILE"
  exit 0
fi

schema_file="sql/wcc_ddl_schema.sql"
schema_present=false
filtered=()
for f in "${FILES[@]}"; do
  base="$(basename "$f")"
  if [[ "$base" == "$(basename "$DEPLOY_FILE")" ]]; then
    continue
  fi
  if [[ "$base" == "$(basename "$schema_file")" ]]; then
    schema_present=true
    continue
  fi
  filtered+=("$f")
done

if "$schema_present"; then
  FILES=("$schema_file" "${filtered[@]}")
else
  FILES=("${filtered[@]}")
fi

# --- 2.5) collect items SQL files ---
mapfile -t ITEMS_FILES < <(ls -1 sql/items/[0-9][0-9][0-9]_*.sql 2>/dev/null | sort)

if [ "${#FILES[@]}" -eq 0 ] && [ "${#ITEMS_FILES[@]}" -eq 0 ]; then
  echo "[seed] only found $DEPLOY_FILE, nothing to merge"
  exit 0
fi

echo "[seed] merging SQL files into $DEPLOY_FILE:"
printf ' - %s\n' "${FILES[@]}"
if [ "${#ITEMS_FILES[@]}" -gt 0 ]; then
  echo "[seed] items SQL files (will be appended):"
  printf ' - %s\n' "${ITEMS_FILES[@]}"
fi

# --- 3) build combined file ---
# Function to remove UTF-8 BOM (EF BB BF) from file content
remove_bom() {
  # Remove BOM using perl if available (most reliable)
  # BOM in UTF-8 is the bytes EF BB BF, which is Unicode character U+FEFF
  if command -v perl >/dev/null 2>&1; then
    perl -pe 's/^\xEF\xBB\xBF//' "$1" 2>/dev/null || cat "$1"
  else
    # Fallback: just output file as-is (BOM will remain but shouldn't cause issues in most cases)
    cat "$1"
  fi
}

{
  echo "-- generated by db/seed.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  for f in "${FILES[@]}"; do
    echo
    echo "-- >>> BEGIN $f"
    echo
    remove_bom "$f"
    echo
    echo "-- <<< END $f"
  done
  # Append items files at the end
  if [ "${#ITEMS_FILES[@]}" -gt 0 ]; then
    for f in "${ITEMS_FILES[@]}"; do
      echo
      echo "-- >>> BEGIN $f"
      echo
      remove_bom "$f"
      echo
      echo "-- <<< END $f"
    done
  fi
} > "$DEPLOY_FILE"

# Optional: stop here.
if [ "$WCC_SEED_MERGE_ONLY" = "true" ]; then
  echo "[seed] merge-only mode enabled; generated $DEPLOY_FILE and exiting without applying."
  exit 0
fi

# --- 4) apply combined file ---
echo "[seed] applying $DEPLOY_FILE"
if "$use_container"; then
  docker compose exec -T postgres psql \
    -U "$POSTGRES_USER" \
    -d "$POSTGRES_DB" \
    -v ON_ERROR_STOP=1 \
    -f - < "$DEPLOY_FILE"
else
  PGPASSWORD="${POSTGRES_PASSWORD:-}" psql \
    -h "$POSTGRES_HOST" \
    -p "$POSTGRES_PORT" \
    -U "$POSTGRES_USER" \
    -d "$POSTGRES_DB" \
    -v ON_ERROR_STOP=1 \
    -f "$DEPLOY_FILE"
fi

echo "[seed] done."
