CREATE TABLE IF NOT EXISTS wcc_item_recipes (
    r_id            varchar(10) PRIMARY KEY,          -- e.g. 'R001'
    dlc_dlc_id      varchar(64) NOT NULL REFERENCES wcc_dlcs(dlc_id), -- source_id (core, hb, dlc_*, exp_*)

    name_id         uuid NOT NULL,                    -- ck_id('witcher_cc.items.recipe.name.'||r_id)

    -- Reused dictionary fields (see 001_wcc_items_dict.sql)
    group_id        uuid NULL,                        -- ck_id('reciples.group.*')
    availability_id uuid NULL,                        -- ck_id('availability.*')
    craft_level_id uuid NULL,                        -- ck_id('craft.level.*')

    weight          numeric(12,1) NULL,
    minimal_ingredients_cost integer NULL,
    price_potion    integer NULL,
    price_formula   integer NULL,
    complexity      integer NULL,
    time_craft_val  text NULL,
    time_craft_unit_id uuid NULL,                     -- ck_id('time.unit.*')
    time_effect_val text NULL,
    time_effect_unit_id uuid NULL,                   -- ck_id('time.unit.*')
    toxicity        text NULL,

    formula         uuid[] NULL,                      -- Array of ingredient UUIDs

    description_id  uuid NOT NULL                     -- ck_id('witcher_cc.items.recipe.description.'||r_id)
);

COMMENT ON TABLE wcc_item_recipes IS
  'Алхимические рецепты. Источник (DLC) через wcc_dlcs, локализуемые поля через i18n_text UUID (ck_id). Группа/уровень крафта/доступность/единицы времени — из общего словаря (001_wcc_items_dict.sql).';

COMMENT ON COLUMN wcc_item_recipes.dlc_dlc_id IS
  'FK на wcc_dlcs.dlc_id (источник/пакет: core/hb/dlc_*/exp_*).';

COMMENT ON COLUMN wcc_item_recipes.name_id IS
  'i18n UUID для названия рецепта. Генерируется детерминированно: ck_id(''witcher_cc.items.recipe.name.''||r_id).';

COMMENT ON COLUMN wcc_item_recipes.description_id IS
  'i18n UUID для описания рецепта. Генерируется детерминированно: ck_id(''witcher_cc.items.recipe.description.''||r_id).';

COMMENT ON COLUMN wcc_item_recipes.formula IS
  'Массив UUID ингредиентов из словаря (ingredients.*).';

-- Helper function to map Russian ingredient name to dictionary key
CREATE OR REPLACE FUNCTION map_ingredient_ru_to_key(ing_name text)
RETURNS text AS $$
BEGIN
  RETURN CASE
    WHEN ing_name = 'Купорос' THEN 'ingredients.vitriol'
    WHEN ing_name = 'Ребис' THEN 'ingredients.rebis'
    WHEN ing_name = 'Эфир' THEN 'ingredients.aether'
    WHEN ing_name = 'Квебрит' THEN 'ingredients.quebrith'
    WHEN ing_name = 'Гидраген' THEN 'ingredients.hydragenum'
    WHEN ing_name = 'Киноварь' THEN 'ingredients.vermilion'
    WHEN ing_name = 'Аер' THEN 'ingredients.caelum'
    WHEN ing_name = 'Фульгор' THEN 'ingredients.fulgur'
    WHEN ing_name = 'Солнце' THEN 'ingredients.sol'
    WHEN ing_name = 'Мутаген' THEN 'ingredients.mutagen'
    WHEN ing_name = 'Крепкий алкоголь' THEN 'ingredients.spirits'
    ELSE NULL
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Helper function to parse formula string and convert to UUID array
CREATE OR REPLACE FUNCTION parse_formula_to_uuid_array(formula_text text)
RETURNS uuid[] AS $$
DECLARE
  result uuid[];
  parts text[];
  part text;
  ing_key text;
BEGIN
  IF formula_text IS NULL OR trim(formula_text) = '' THEN
    RETURN NULL;
  END IF;
  
  -- Split by comma and trim each part
  parts := string_to_array(formula_text, ',');
  result := ARRAY[]::uuid[];
  
  FOREACH part IN ARRAY parts
  LOOP
    part := trim(part);
    IF part != '' THEN
      ing_key := map_ingredient_ru_to_key(part);
      IF ing_key IS NOT NULL THEN
        result := array_append(result, ck_id(ing_key));
      END IF;
    END IF;
  END LOOP;
  
  RETURN result;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

WITH raw_data (
  r_id, source_id, group_key, availability_key,
  name_ru, name_en,
  weight, minimal_ingredients_cost, price_potion, price_formula,
  craft_level_key, complexity,
  time_craft_val, time_craft_unit_key,
  time_effect_val, time_effect_unit_key,
  toxicity,
  formula_text,
  description_ru, description_en
) AS ( VALUES
  ('R001','core','reciples.group.potion','availability.U',
    'Белый мёд','White Honey',
    '0,5',21,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    NULL,NULL,
    NULL,
    'Купорос, Ребис, Эфир',
    'Отменяет эффекты и токсичность всех элексиров.','Cancels effects and toxicity of all elixirs.'),
  ('R002','core','reciples.group.potion','availability.U',
    'Гром','Thunderbolt',
    '0,5',20,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '15','time.unit.round',
    '75%',
    'Квебрит, Квебрит, Гидраген, Гидраген',
    'Доп. Урон физическими атаками (+3)','Additional Damage with physical attacks (+3)'),
  ('R003','dlc_rw4','reciples.group.elixir','availability.P',
    'Выносливости','Endurance Potion',
    '0,5',NULL,75,NULL,
    'craft.level.master',17,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '50%',
    'Эфир, Эфир, Аер, Киноварь, Киноварь',
    'Восстанавливает 3d6 очков выносливости.','Restores 3d6 Endurance points.'),
  ('R004','dlc_rw4','reciples.group.elixir','availability.P',
    'Живучести','Vitality Potion',
    '0,5',NULL,85,NULL,
    'craft.level.master',18,
    '30','time.unit.minute',
    '2d6','time.unit.round',
    '50%',
    'Купорос, Фульгор, Фульгор, Гидраген, Ребис, Ребис',
    'Можно игнорировать штрафы сосотяния ранения.','You can ignore penalties from wound condition.'),
  ('R005','core','reciples.group.potion','availability.U',
    'Зелье Петри','Petri''s Filter',
    '0,5',15,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '15','time.unit.round',
    '75%',
    'Ребис, Эфир, Квебрит',
    'Доп. Сотворение заклинаний (+2); Доп. Наведение порчи (+2); Доп. Проведение ритуалов (+2)','Additional Spell Casting (+2); Additional Hex Weaving (+2); Additional Ritual Crafting (+2)'),
  ('R006','dlc_rw4','reciples.group.elixir','availability.R',
    'Раффара Белого','White Raffard''s Decoction',
    '0,5',NULL,95,NULL,
    'craft.level.master',19,
    '30','time.unit.minute',
    '4d6','time.unit.round',
    '50%',
    'Эфир, Аер, Квебрит, Ребис, Киноварь, Купорос',
    'Восстанавливает 1 ПЗ за раунд','Restores 1 HP per round'),
  ('R007','core','reciples.group.potion','availability.U',
    'Иволга','Golden Oriole',
    '0,5',25,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '50%',
    'Ребис, Киноварь, Аер',
    'Даёт невосприимчивость к ядам и нейтрализует все яды.','Grants immunity to poisons and neutralizes all poisons.'),
  ('R008','core','reciples.group.potion','availability.U',
    'Косатка','Killer Whale',
    '0,5',28,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '25%',
    'Купорос, Купорос, Квебрит, Фульгор',
    'Доп. время задержки дыхания (50%); Отменяет штрафы к зрению под водой.','Additional breath-holding time (50%); Cancels penalties to vision underwater.'),
  ('R009','core','reciples.group.potion','availability.U',
    'Кошка','Cat',
    '0,5',22,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '2','time.unit.hour',
    '25%',
    'Эфир, Киноварь, Гидраген',
    'Ночное зрение (+); Невосприимчивость к гипнозу; Доп. Раскрытие иллюзий (+2)','Night vision (+); Immunity to hypnosis; Additional illusion detection (+2)'),
  ('R010','core','reciples.group.potion','availability.U',
    'Ласточка','Swallow',
    '0,5',21,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '20','time.unit.round',
    '50%',
    'Купорос, Эфир, Аер',
    'Восстанавливает 3 ПЗ за раунд, если нет попаданий по вам.; Не стакается.','Restores 3 HP per round if you haven''t been hit.; Does not stack.'),
  ('R011','core','reciples.group.potion','availability.U',
    'Лес Марибора','Maribor Forest',
    '0,5',43,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '15','time.unit.round',
    '50%',
    'Ребис, Киноварь, Аер, Солнце',
    'Удваивает дайсы адреналина.','Doubles adrenaline dice.'),
  ('R012','core','reciples.group.potion','availability.U',
    'Неясыть','Tawny Owl',
    '0,5',19,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '20','time.unit.round',
    '50%',
    'Купорос, Киноварь, Квебрит',
    'Доп. восстановление Выносливости (+2) при отдыхе.','Additional Endurance recovery (+2) when resting.'),
  ('R013','core','reciples.group.potion','availability.U',
    'Полнолуние','Full Moon',
    '0,5',36,NULL,NULL,
    NULL,20,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Квебрит, Гидраген, Гидраген, Киноварь, Киноварь',
    'Доп. Здоровье (+30).; Не стакается.','Additional Health (+30).; Does not stack.'),
  ('R014','core','reciples.group.potion','availability.U',
    'Пурга','Blizzard',
    '0,5',32,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '10','time.unit.round',
    '75%',
    'Купорос, Купорос, Ребис, Ребис, Эфир',
    'Доп. Реакция (+4) после первого убийства противника.','Additional Reaction (+4) after first enemy kill.'),
  ('R015','core','reciples.group.potion','availability.U',
    'Чёрная кровь','Black Blood',
    '0,5',37,NULL,NULL,
    NULL,20,
    '30','time.unit.minute',
    '20','time.unit.round',
    '25%',
    'Купорос, Купорос, Купорос, Ребис, Эфир',
    'Испитая кровь отравляет на (3). Преодоление отравления через Стойкость со СЛ20.; Укусивший противник отскакивает на 2м.','Drunk blood poisons for (3). Overcome poisoning with Endurance DC 20.; Biting enemy is knocked back 2m.'),
  ('R016','core','reciples.group.oil','availability.U',
    'Против вампиров','Vampire Oil',
    '0,5',61,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Эфир, Солнце, Солнце, Фульгор',
    '(+5) урона против вампиров','(+5) damage against vampires'),
  ('R017','core','reciples.group.oil','availability.U',
    'Против гибридов','Hybrid Oil',
    '0,5',48,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Ребис, Солнце, Квебрит, Фульгор',
    '(+5) урона против гибридов','(+5) damage against hybrids'),
  ('R018','core','reciples.group.oil','availability.U',
    'Против драконидов','Draconid Oil',
    '0,5',30,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Квебрит, Квебрит, Гидраген, Гидраген',
    '(+5) урона против драконидов','(+5) damage against draconids'),
  ('R019','core','reciples.group.oil','availability.U',
    'Против духов','Specter Oil',
    '0,5',41,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Ребис, Гидраген, Эфир, Фульгор',
    '(+5) урона против духов стихий','(+5) damage against elementals'),
  ('R020','core','reciples.group.oil','availability.U',
    'Против духов стихий','Elementa Oil',
    '0,5',37,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Ребис, Гидраген, Квебрит, Киноварь',
    '(+5) урона против духов стихий','(+5) damage against elementals'),
  ('R021','core','reciples.group.oil','availability.U',
    'Против зверей','Beast Oil',
    '0,5',23,NULL,NULL,
    NULL,14,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Купорос, Эфир',
    '(+5) урона против зверей','(+5) damage against beasts'),
  ('R022','core','reciples.group.oil','availability.U',
    'Против инсектоидов','Insectoid Oil',
    '0,5',26,NULL,NULL,
    NULL,14,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Гидраген, Ребис',
    '(+5) урона против инсектоидов','(+5) damage against insectoids'),
  ('R023','core','reciples.group.oil','availability.U',
    'Против огров','Ogroid Oil',
    '0,5',28,NULL,NULL,
    NULL,15,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Ребис, Квебрит, Аер',
    '(+5) урона против огров','(+5) damage against ogroids'),
  ('R024','core','reciples.group.oil','availability.U',
    'Против проклятых','Cursed Oil',
    '0,5',40,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Киноварь, Эфир, Гидраген, Купорос',
    '(+5) урона против проклятых','(+5) damage against cursed'),
  ('R025','core','reciples.group.oil','availability.U',
    'Против реликтов','Relict Oil',
    '0,5',36,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Квебрит, Киноварь, Фульгор, Эфир',
    '(+5) урона против реликтов','(+5) damage against relicts'),
  ('R026','core','reciples.group.oil','availability.U',
    'Против трупоедов','Necrophage Oil',
    '0,5',46,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Гидраген, Солнце, Купорос, Квебрит',
    '(+5) урона против трупоедов','(+5) damage against necrophages'),
  ('R027','core','reciples.group.oil','availability.U',
    'Яд повешенного','Hanged Man''s Venom',
    '0,5',46,NULL,NULL,
    NULL,16,
    '15','time.unit.minute',
    '30','time.unit.minute',
    NULL,
    'Аер, Солнце, Купорос, Квебрит',
    '(+5) урона против гуманоидов','(+5) damage against humanoids'),
  ('R028','core','reciples.group.decoction','availability.U',
    'Бес','Fiend',
    '0,5',67,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Эфир, Эфир, Купорос, Киноварь, Фульгор, Мутаген, Крепкий алкоголь',
    'Доп. Переносимый вес (+100%)','Additional Encumbrance (+100%)'),
  ('R029','core','reciples.group.decoction','availability.U',
    'Виверна','Wyvern',
    '0,5',69,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Ребис, Ребис, Купорос, Эфир, Фульгор, Мутаген, Крепкий алкоголь',
    'Доп. Урон (+1) к следующему после попавшему удару.; Стакается.; Действует до конца боя или получения урона.','Additional Damage (+1) to next hit after a successful strike.; Stacks.; Lasts until end of combat or taking damage.'),
  ('R030','core','reciples.group.decoction','availability.U',
    'Волколак','Werewolf',
    '0,5',82,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Ребис, Солнце, Гидраген, Гидраген, Фульгор, Мутаген, Крепкий алкоголь',
    'Длительный бег не требует затрат Выносливости.','Extended running does not cost Endurance.'),
  ('R031','core','reciples.group.decoction','availability.U',
    'Главоглаз','Arachas',
    '0,5',60,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Киноварь, Эфир, Ребис, Купорос, Мутаген, Крепкий алкоголь',
    'Доп. ПБ (+2) всех частей тела за каждые 10 свободных очков Переносимого веса.','Additional Armor (+2) to all body parts for every 10 free Encumbrance points.'),
  ('R032','core','reciples.group.decoction','availability.U',
    'Грифон','Griffin',
    '0,5',56,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Квебрит, Киноварь, Фульгор, Эфир, Мутаген, Крепкий алкоголь',
    'Доп. (+2) ПБ за получение урона выше 5.; Стакается.; Общий бонус на все части тела.','Additional (+2) Armor when taking damage above 5.; Stacks.; General bonus to all body parts.'),
  ('R033','core','reciples.group.decoction','availability.U',
    'Катакан','Katakan',
    '0,5',75,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Киноварь, Солнце, Фульгор, Аер, Мутаген, Крепкий алкоголь',
    'Доп. Значение броска (+3) при определении места крит. ранения','Additional roll value (+3) when determining critical wound location'),
  ('R034','core','reciples.group.decoction','availability.U',
    'Кладбищенская баба','Grave Hag',
    '0,5',53,NULL,NULL,
    NULL,16,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Эфир, Квебрит, Купорос, Аер, Мутаген, Крепкий алкоголь',
    'Доп. Регенрация ПЗ (+2) за каждого убитого врага до окончания боя.','Additional HP regeneration (+2) per killed enemy until end of combat.'),
  ('R035','core','reciples.group.decoction','availability.U',
    'Накера','Nekker',
    '0,5',48,NULL,NULL,
    NULL,14,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Ребис, Квебрит, Гидраген, Мутаген, Крепкий алкоголь',
    'Доп. Верховая езда (+3); Доп. Атлетика (+3); Ваш скакун никогда не паникует','Additional Riding (+3); Additional Athletics (+3); Your mount never panics'),
  ('R036','core','reciples.group.decoction','availability.U',
    'Полуденницы','Noon Wraith',
    '0,5',81,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Солнце, Солнце, Купорос, Квебрит, Эфир, Мутаген, Крепкий алкоголь',
    'Невосприимчивость к дезориентации и слепоте; Вас нельзя сбить с ног.','Immunity to disorientation and blindness; You cannot be knocked down.'),
  ('R037','core','reciples.group.decoction','availability.U',
    'Скальный тролль','Troll',
    '0,5',59,NULL,NULL,
    NULL,18,
    '30','time.unit.minute',
    '30','time.unit.minute',
    '75%',
    'Аер, Квебрит, Квебрит, Купорос, Киноварь, Мутаген, Крепкий алкоголь',
    'Восстанавливает 5 ПЗ за раунд.','Restores 5 HP per round.'),
  ('R038','dlc_rw2','reciples.group.alchemical_item','availability.R',
    'Адреналиновый эликсир','Adrenal Elixir',
    '0,1',NULL,100,150,
    'craft.level.master',20,
    '30','time.unit.minute',
    '3','time.unit.round',
    NULL,
    'Аер, Фульгор, Квебрит, Ребис, Ребис, Солнце, Киноварь',
    'Снижение СЛ стабилизации на (-5); Успешность спасбросков от смерти и мгнорирование штрафов состояния ранения','Reduces stabilization DC by (-5); Success on death saving throws and ignoring penalties from wound condition'),
  ('R039','core','reciples.group.alchemical_item','availability.C',
    'Алхимический клей','Alchemical Adhesive',
    '0,1',NULL,28,52,
    'craft.level.journeyman',15,
    '10','time.unit.minute',
    NULL,NULL,
    NULL,
    'Квебрит, Гидраген, Аер, Аер, Купорос',
    'Навсегда склеивает что угодно если вылить или метнуть на 2*Тел метров (через Атлетику). Затвердевает через 2 хода. Для разъединения проверка Силы со СЛ16.','Permanently bonds anything if poured or thrown at 2*BODY meters (via Athletics). Hardens after 2 rounds. Separation requires Physique check DC 16.'),
  ('R040','core','reciples.group.alchemical_item','availability.P',
    'Ароматное зелье','Perfume Potion',
    '0,5',NULL,76,114,
    'craft.level.master',18,
    '30','time.unit.minute',
    '1d10','time.unit.hour',
    '25%',
    'Квебрит, Квебрит, Эфир, Купорос, Купорос, Киноварь, Гидраген, Гидраген',
    'Алкогольное. Бросьте Стойкость со СЛ 16. При провале получаете обпьянение.','Alcoholic. Roll Endurance DC 16. On failure you become intoxicated.'),
  ('R041','core','reciples.group.alchemical_item','availability.P',
    'Быстрый огонь','Quick Fire',
    '0,1',NULL,45,67,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    NULL,NULL,
    NULL,
    'Квебрит, Ребис, Ребис, Аер, Купорос, Киноварь',
    'Быстро сохнет. Облитая поверхность воспламеняется с шансом 50% от любого контакта с искрой или огнём.','Quick-drying. Coated surface ignites with 50% chance from any contact with spark or fire.'),
  ('R042','core','reciples.group.alchemical_item','availability.C',
    'Галлюциноген','Hallucinogen',
    '0,1',NULL,25,47,
    'craft.level.novice',12,
    '5','time.unit.round',
    '1d10','time.unit.round',
    NULL,
    'Купорос, Ребис',
    'При потреблении или став целью броска (3 метра) жертва бросает Стойкость со СЛ15. При провале получает галлюцинации.','When consumed or as target of throw (3 meters) victim rolls Endurance DC 15. On failure receives hallucinations.'),
  ('R043','core','reciples.group.alchemical_item','availability.C',
    'Друг отравителя','Poisoner''s Friend',
    '0,1',NULL,16,24,
    'craft.level.novice',14,
    '10','time.unit.minute',
    NULL,NULL,
    NULL,
    'Киноварь, Киноварь, Купорос, Аер',
    'Прозрачный. Имеет острый или сладкий вкус. Поможет скрыть яд, который теперь обнаруживается со СЛ 20.','Transparent. Has sharp or sweet taste. Helps conceal poison, which is now detected with DC 20.'),
  ('R044','core','reciples.group.alchemical_item','availability.C',
    'Дыхание суккуба','Succubus'' Breath',
    '0,1',NULL,20,30,
    'craft.level.novice',14,
    '10','time.unit.minute',
    NULL,NULL,
    NULL,
    'Солнце, Эфир, Эфир, Аер',
    'Доп. Соблазнение (+2) при втирании. Снижение защиты от Соблазнения на (-5) при распитии (обнаруживается через Внимание со СЛ16).','Additional Seduction (+2) when applied. Reduces defense against Seduction by (-5) when drunk (detected via Awareness DC 16).'),
  ('R045','exp_lal','reciples.group.alchemical_item','availability.R',
    'Зелье берсерка','Berserker''s Brew',
    '0,1',NULL,105,NULL,
    'craft.level.master',22,
    '30','time.unit.minute',
    '1d10','time.unit.round',
    NULL,
    'Ребис, Ребис, Ребис, Солнце, Аер, Аер, Фульгор, Квебрит',
    'Выпившая жертва каждый ход атакует ближайшего персонажа, если провалила Стойкость со СЛ16 в этот ход, независимо от прошлых бросков.','Drinking victim attacks nearest character each round if failed Endurance DC 16 this round, regardless of previous rolls.'),
  ('R046','core','reciples.group.alchemical_item','availability.P',
    'Зерриканский огонь','Zerrikanian Fire',
    '0,5',NULL,65,97,
    'craft.level.master',17,
    '15','time.unit.minute',
    NULL,NULL,
    NULL,
    'Солнце, Солнце, Ребис, Ребис, Ребис, Фульгор, Купорос',
    'Поджигающая жидкость. Можно метнуть на 2*Тел метров через Атлетику. Зона поражения - конус 2 метра от места падения.','Igniting liquid. Can be thrown at 2*BODY meters via Athletics. Damage area - 2 meter cone from impact point.'),
  ('R047','core','reciples.group.alchemical_item','availability.P',
    'Кислотный раствор','Acid Solution',
    '0,5',NULL,56,84,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    NULL,NULL,
    NULL,
    'Эфир, Квебрит, Киноварь, Купорос, Купорос, Купорос',
    'Наносит урон 2d6 и повреждает оружие с бронёй на 1d6/2. Можно метнуть на 2*Тел метров через Атлетику. Зона поражения - конус 2 метра от места падения.','Deals 2d6 damage and damages weapons with armor by 1d6/2. Can be thrown at 2*BODY meters via Athletics. Damage area - 2 meter cone from impact point.'),
  ('R048','core','reciples.group.alchemical_item','availability.C',
    'Кровосвёртывающий порошок','Clotting Powder',
    '0,1',NULL,20,30,
    'craft.level.novice',12,
    '5','time.unit.round',
    '1d10','time.unit.round',
    NULL,
    'Эфир, Ребис',
    'Временно останавливает кровотечение, но не снимает этот эффект.','Temporarily stops bleeding, but does not remove this effect.'),
  ('R049','exp_lal','reciples.group.alchemical_item','availability.C',
    'Летняя мазь','Summer Ointment',
    '0,1',NULL,22,NULL,
    'craft.level.novice',12,
    '5','time.unit.round',
    NULL,NULL,
    NULL,
    'Квебрит, Эфир',
    'Удваивает время нахождения на морозе. Снижает штраф к Выносливости от жары до 1/4 Выносливости.','Doubles time spent in cold. Reduces Endurance penalty from heat to 1/4 Endurance.'),
  ('R050','core','reciples.group.alchemical_item','availability.C',
    'Могила Адды','Adda''s Tomb',
    '0,1',NULL,18,27,
    'craft.level.novice',13,
    '5','time.unit.round',
    '1d10','time.unit.day',
    NULL,
    'Эфир, Эфир, Гидраген, Киноварь',
    'Обработанные продукты или труп не будут портиться или гнить. Телу нужно 2 порции.','Treated food or corpse will not spoil or rot. Body requires 2 doses.'),
  ('R051','core','reciples.group.alchemical_item','availability.C',
    'Невидимые чернила','Invisible Ink',
    '0,1',NULL,15,22,
    'craft.level.novice',11,
    '5','time.unit.round',
    NULL,NULL,
    NULL,
    'Квебрит, Эфир',
    'Позволяют писать сообщения, прочесть которые можно только после нагревания в течение 1 хода.','Allows writing messages that can only be read after heating for 1 round.'),
  ('R052','core','reciples.group.alchemical_item','availability.C',
    'Нюхательная соль','Smelling Salts',
    '0,1',NULL,25,37,
    'craft.level.novice',14,
    '10','time.unit.minute',
    NULL,NULL,
    NULL,
    'Квебрит, Ребис, Аер, Аер',
    'Снимает эффекты дезориентации и потери сознания. (25) Применений.','Removes effects of disorientation and unconsciousness. (25) Uses.'),
  ('R053','core','reciples.group.alchemical_item','availability.E',
    'Обезболивающие травы','Numbing Herbs',
    '0,1',NULL,12,18,
    'craft.level.novice',12,
    '5','time.unit.round',
    '2d10','time.unit.round',
    NULL,
    'Квебрит, Киноварь',
    'Снижает штраф от крит ранений и/или состояния "при смерти" на (-2).','Reduces penalty from critical wounds and/or "at death''s door" condition by (-2).'),
  ('R054','core','reciples.group.alchemical_item','availability.C',
    'Обеззараживающая жидкость','Sterilizing Fluid',
    '0,1',NULL,22,33,
    'craft.level.novice',12,
    '5','time.unit.round',
    NULL,NULL,
    NULL,
    'Квебрит, Аер',
    'Доп. скорость естественного исцеления (+2). Снижение срока исценления крит.раны на (-2) дней. Не стакается.','Additional natural healing speed (+2). Reduces critical wound healing time by (-2) days. Does not stack.'),
  ('R055','dlc_rw2','reciples.group.alchemical_item','availability.P',
    'Пепельная мазь','Ashen Ointment',
    '0,1',NULL,75,125,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    '60','time.unit.minute',
    NULL,
    'Эфир, Эфир, Фульгор, Фульгор, Фульгор, Гидраген',
    'Позволяет игнорировать состояние горения.','Allows ignoring burning condition.'),
  ('R056','dlc_rw2','reciples.group.alchemical_item','availability.C',
    'Помощник следователя','Investigator''s Helper',
    '0,1',NULL,30,60,
    'craft.level.novice',14,
    '10','time.unit.minute',
    NULL,NULL,
    NULL,
    'Киноварь, Купорос, Купорос',
    'Реагирует на следы крови (становится чёрной). (10) Применений.','Reacts to blood traces (turns black). (10) Uses.'),
  ('R057','exp_lal','reciples.group.alchemical_item','availability.P',
    'Селестин','Celestine',
    '0,1',NULL,62,NULL,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    '2d10','time.unit.minute',
    NULL,
    'Гидраген, Гидраген, Эфир, Эфир, Киноварь',
    'Лёгкий наркотик (цветные огни и приятные звуки). Штраф к Вниманию и любой сосредоточенной деятельности (-2). Можно преодолеть Стойкостью со СЛ 14.','Light drug (colored lights and pleasant sounds). Penalty to Awareness and any focused activity (-2). Can be overcome with Endurance DC 14.'),
  ('R058','core','reciples.group.alchemical_item','availability.P',
    'Слёзы жён','Wive''s Tears Potion',
    '0,1',NULL,56,28,
    'craft.level.novice',14,
    '10','time.unit.minute',
    NULL,NULL,
    NULL,
    'Гидраген, Эфир, Эфир, Купорос',
    'Отменяет любые эффекты опьянения.','Cancels any intoxication effects.'),
  ('R059','core','reciples.group.alchemical_item','availability.P',
    'Слёзы Тальгара','Talgar''s Tears',
    '0,1',NULL,79,118,
    'craft.level.master',20,
    '30','time.unit.minute',
    NULL,NULL,
    NULL,
    'Гидраген, Гидраген, Гидраген, Эфир, Эфир, Киноварь, Купорос, Купорос',
    'Заморозкой удваивает разрушающий урон на предмет. Можно метнуть на 2*Тел метров через Атлетику. Зона поражения - конус 2 метра от места падения.','Freezing doubles destructive damage to object. Can be thrown at 2*BODY meters via Athletics. Damage area - 2 meter cone from impact point.'),
  ('R060','exp_lal','reciples.group.alchemical_item','availability.P',
    'Трупный яд','Cadaverine Solution',
    '0,1',NULL,76,NULL,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    NULL,NULL,
    NULL,
    'Киноварь, Киноварь, Киноварь, Киноварь, Фульгор, Ребис',
    'Оружейная мазь. Даёт острому оружию эффекты отравления и тошноты (можно преодолеть по отдельности Стойкостью со СЛ 16).','Weapon ointment. Gives sharp weapons poisoning and nausea effects (can be overcome separately with Endurance DC 16).'),
  ('R061','core','reciples.group.alchemical_item','availability.P',
    'Фисштех','Fisstech',
    '0,1',NULL,80,120,
    'craft.level.master',18,
    '30','time.unit.minute',
    NULL,NULL,
    NULL,
    'Ребис, Ребис, Ребис, Гидраген, Гидраген, Купорос, Купорос, Киноварь',
    'Погружает в подобную трансу эйфорию. Эффект анальгетика. Бросьте Стойкость со СЛ 18, при провале становитесь зависимы.','Plunges into trance-like euphoria. Analgesic effect. Roll Endurance DC 18, on failure you become addicted.'),
  ('R062','core','reciples.group.alchemical_item','availability.C',
    'Хлороформ','Chloroform',
    '0,1',NULL,36,54,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    NULL,NULL,
    NULL,
    'Квебрит, Квебрит, Киноварь, Киноварь, Эфир, Купорос',
    'Жертва теряет сознание при провале испытания Устойчивости со штрафом (-2) пока не пройдет испытание. (25) Применений одной склянки.','Victim loses consciousness on failed Endurance test with penalty (-2) until test is passed. (25) Uses per vial.'),
  ('R063','core','reciples.group.alchemical_item','availability.C',
    'Чёрный яд','Black Venom',
    '0,1',NULL,45,67,
    'craft.level.journeyman',15,
    '10','time.unit.minute',
    NULL,NULL,
    NULL,
    'Квебрит, Квебрит, Эфир, Эфир, Ребис',
    'Оружейная мазь или зелье с эффектом Отравления. Обнаруживается в еде через Внимание со СЛ16. Снятие эффекта через Стойкость со СЛ16.','Weapon ointment or potion with Poisoning effect. Detected in food via Awareness DC 16. Effect removal via Endurance DC 16.'),
  ('R064','core','reciples.group.alchemical_item','availability.C',
    'Щелочной порошок','Base Powder',
    '0,1',NULL,18,27,
    'craft.level.novice',12,
    '5','time.unit.round',
    NULL,NULL,
    NULL,
    'Киноварь, Квебрит',
    'Снимает эффекты порции кислоты. Отменяет урон от крит.ранения "Рана" в живот.','Removes effects of acid dose. Cancels damage from critical wound "Wound" to abdomen.'),
  ('R065','core','reciples.group.alchemical_item','availability.P',
    'Эликсир Пантаграна','Pantagran''s Elixir',
    '0,5',NULL,67,100,
    'craft.level.master',17,
    '15','time.unit.minute',
    '(1d6)/2','time.unit.round',
    NULL,
    'Киноварь, Киноварь, Эфир, Эфир, Аер, Солнце, Фульгор',
    'Наркотик с эффектом безумного счастья. Штраф (-2) к защите от Убеждения, Харизмы, Соблазнения.','Drug with effect of mad happiness. Penalty (-2) to defense against Persuasion, Charisma, Seduction.'),
  ('R066','dlc_rw2','reciples.group.alchemical_item','availability.P',
    'Яд аконита','Monkshood Poison',
    '0,1',NULL,100,150,
    'craft.level.master',18,
    '30','time.unit.minute',
    NULL,NULL,
    NULL,
    'Эфир, Аер, Аер, Ребис, Купорос, Купорос, Купорос',
    'Мелкодисперсный белый ядовитый порошок, отравляющий удушением. Преодолевается броском Выносливости со СЛ 20, или чужой Первой помощью СЛ 20.','Fine white poisonous powder, poisoning by suffocation. Overcome with Endurance roll DC 20, or another''s First Aid DC 20.'),
  ('R067','dlc_rw2','reciples.group.alchemical_item','availability.P',
    'Ядовитая помада','Poisonous Lipstick',
    '0,1',NULL,80,120,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    '60','time.unit.minute',
    NULL,
    'Гидраген, Гидраген, Квебрит, Квебрит, Купорос, Купорос',
    'Следующий человек, которого пользователь целует в течение часа с момента нанесения получает Отравление и Опьянение на время действия. (3) Применения.','Next person user kisses within an hour of application receives Poisoning and Intoxication for duration. (3) Uses.'),
  ('R068','core','reciples.group.alchemical_item','availability.R',
    'Ярость Бредана','Bredan''s Fury',
    '0,5',NULL,95,142,
    'craft.level.master',22,
    '30','time.unit.minute',
    NULL,NULL,
    NULL,
    'Солнце, Солнце, Солнце, Фульгор, Фульгор, Фульгор, Аер, Киноварь',
    'Взрывается при контакте с воздухом, нанося 2d6 урона в радуесе 2м.Можно метнуть на 2*Тел метров через Атлетику.','Explodes on contact with air, dealing 2d6 damage in 2m radius. Can be thrown at 2*BODY meters via Athletics.'),
  ('R069','core','reciples.group.medicine','availability.C',
    'Прилив сил','Energy Surge',
    '0,1',NULL,0,0,
    'craft.level.novice',18,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Купорос, Ребис',
    'Доп. Здоровье (+15)','Additional Health (+15)'),
  ('R070','core','reciples.group.medicine','availability.C',
    'Анальгетик','Analgesic',
    '0,1',NULL,0,0,
    'craft.level.novice',14,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Квебрит, Солнце',
    'Снижает на (-4) штрафы от крит. ранений и состояния при смерти','Reduces penalties from critical wounds and at death''s door condition by (-4)'),
  ('R071','core','reciples.group.medicine','availability.C',
    'Светочувствительность','Photosensitivity',
    '0,1',NULL,0,0,
    'craft.level.novice',14,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Эфир, Аер',
    'Отменяет штрафы за слабое освещение, удваивает штрафы за яркий свет.','Cancels penalties for dim lighting, doubles penalties for bright light.'),
  ('R072','core','reciples.group.medicine','availability.C',
    'Успокоительное','Sedative',
    '0,1',NULL,0,0,
    'craft.level.novice',15,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Фульгор, Киноварь',
    'Доп. Запугивание (+3)','Additional Intimidation (+3)'),
  ('R073','core','reciples.group.medicine','availability.C',
    'Релаксант','Muscle Relaxant',
    '0,1',NULL,0,0,
    'craft.level.novice',15,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Гидраген, Ребис',
    'Доп. Соблазнение (+3)','Additional Seduction (+3)'),
  ('R074','core','reciples.group.medicine','availability.C',
    'Ноотроп','Nootropic',
    '0,1',NULL,0,0,
    'craft.level.novice',15,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Эфир, Купорос',
    'Доп. Внимание (+3)','Additional Awareness (+3)'),
  ('R075','core','reciples.group.medicine','availability.C',
    'Стимулятор','Stimulant',
    '0,1',NULL,0,0,
    'craft.level.novice',18,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Киноварь, Квебрит',
    'Доп. Выносливость (+15)','Additional Endurance (+15)'),
  ('R076','core','reciples.group.medicine','availability.C',
    'Наркоз','Anesthetic',
    '0,1',NULL,0,0,
    'craft.level.novice',18,
    '1','time.unit.round',
    '1','time.unit.hour',
    NULL,
    'Фульгор, Солнце',
    'Погружает в кому, подобную смерти.','Plunges into coma, similar to death.'),
  ('R077','core','reciples.group.medicine','availability.C',
    'Кофеин','Caffeine',
    '0,1',NULL,0,0,
    'craft.level.novice',17,
    '1','time.unit.round',
    '1','time.unit.day',
    NULL,
    'Аер, Гидраген',
    'Можно не спать ночь без штрафов.','Can stay awake through the night without penalties.'),
  ('R078','core','reciples.group.medicine','availability.C',
    'Нейростимулятор','Neurostimulant',
    '0,1',NULL,0,0,
    'craft.level.novice',15,
    '1','time.unit.round',
    '10','time.unit.round',
    NULL,
    'Киноварь, Солнце',
    'Доп. Реакция (+3)','Additional Reaction (+3)'),
  ('R079','exp_toc','reciples.group.elixir','availability.P',
    'Мангуст','Mongoose',
    '0,1',NULL,50,100,
    'craft.level.journeyman',15,
    '15','time.unit.minute',
    '30','time.unit.minute',
    '50%',
    'Ребис, Ребис, Эфир, Эфир, Фульгор, Фульгор',
    'Невосприимчивость к отравлению.','Immunity to poisoning.'),
  ('R080','exp_toc','reciples.group.elixir','availability.P',
    'Буря','Tempest',
    '0,1',NULL,52,104,
    'craft.level.journeyman',15,
    '15','time.unit.minute',
    NULL,NULL,
    '50%',
    'Купорос, Эфир, Квебрит, Аер, Гидраген',
    'Доп. Вероятность (+10%) горения, замораживания, сбития с ног при атаке с этими эффектами.','Additional probability (+10%) of burning, freezing, knocking down when attacking with these effects.'),
  ('R081','exp_toc','reciples.group.elixir','availability.P',
    'Путник','Strider',
    '0,1',NULL,64,128,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    '1','time.unit.day',
    '50%',
    'Ребис, Ребис, Эфир, Фульгор, Аер',
    'Выпившему не требуется сон.','Drinker does not require sleep.'),
  ('R082','exp_toc','reciples.group.elixir','availability.P',
    'Молния','Lightning',
    '0,1',NULL,75,150,
    'craft.level.journeyman',16,
    '15','time.unit.minute',
    NULL,NULL,
    '75%',
    'Купорос, Купорос, Киноварь, Киноварь, Гидраген, Гидраген',
    'Доп. Урон (+3) к следующей физической атаке.','Additional Damage (+3) to next physical attack.'),
  ('R083','exp_toc','reciples.group.elixir','availability.P',
    'Анаболические стероиды','Anabolic Steroids',
    '0,1',NULL,165,330,
    'craft.level.journeyman',16,
    '30','time.unit.minute',
    '10','time.unit.minute',
    '50%',
    'Ребис, Аер, Квебрит, Гидраген, Гидраген',
    'Доп. Здоровье (+10), Доп. Стойкость (+2), Доп. Сила (+2). Агрессивность на 1ч.','Additional Health (+10), Additional Endurance (+2), Additional Physique (+2). Aggressiveness for 1 hour.'),
  ('R084','exp_toc','reciples.group.elixir','availability.P',
    'Последняя надежда','Last Hope',
    '0,1',NULL,200,400,
    'craft.level.master',22,
    '60','time.unit.minute',
    NULL,NULL,
    '75%',
    'Солнце, Солнце, Купорос, Эфир, Эфир, Киноварь, Киноварь, Киноварь',
    'Купирует (лечит) 1 крит.рану. Но сама она так не излечится. Нужно нанести её повторно Лечащим прикосновением доктора со СЛ24, а потом уж лечить.','Stops (heals) 1 critical wound. But it itself will not heal this way. Must be applied again with doctor''s Healing Touch DC 24, then treat.')
),
ins_i18n AS (
  INSERT INTO i18n_text (id, entity, entity_field, lang, text)
  SELECT * FROM (
    -- Recipe names
    SELECT ck_id('witcher_cc.items.recipe.name.'||rd.r_id),
           'items',
           'recipe_names',
           'ru',
           rd.name_ru
      FROM raw_data rd
     WHERE nullif(rd.name_ru,'') IS NOT NULL
    UNION ALL
    SELECT ck_id('witcher_cc.items.recipe.name.'||rd.r_id),
           'items',
           'recipe_names',
           'en',
           rd.name_en
      FROM raw_data rd
     WHERE nullif(rd.name_en,'') IS NOT NULL
    UNION ALL
    -- Recipe descriptions
    SELECT ck_id('witcher_cc.items.recipe.description.'||rd.r_id),
           'items',
           'recipe_descriptions',
           'ru',
           rd.description_ru
      FROM raw_data rd
     WHERE nullif(rd.description_ru,'') IS NOT NULL
    UNION ALL
    SELECT ck_id('witcher_cc.items.recipe.description.'||rd.r_id),
           'items',
           'recipe_descriptions',
           'en',
           rd.description_en
      FROM raw_data rd
     WHERE nullif(rd.description_en,'') IS NOT NULL
  ) foo
  ON CONFLICT (id, lang) DO NOTHING
)
INSERT INTO wcc_item_recipes (
  r_id, dlc_dlc_id, name_id,
  group_id, availability_id, craft_level_id,
  weight, minimal_ingredients_cost, price_potion, price_formula, complexity,
  time_craft_val, time_craft_unit_id,
  time_effect_val, time_effect_unit_id,
  toxicity,
  formula,
  description_id
)
SELECT rd.r_id
     , rd.source_id AS dlc_dlc_id
     , ck_id('witcher_cc.items.recipe.name.'||rd.r_id) AS name_id
     , ck_id(rd.group_key) AS group_id
     , ck_id(rd.availability_key) AS availability_id
     , CASE WHEN rd.craft_level_key IS NOT NULL AND rd.craft_level_key != '' THEN ck_id(rd.craft_level_key) ELSE NULL END AS craft_level_id
     , CAST(NULLIF(REPLACE(rd.weight, ',', '.'), '') AS numeric) AS weight
     , CAST(NULLIF(rd.minimal_ingredients_cost::text, '') AS integer) AS minimal_ingredients_cost
     , CAST(NULLIF(rd.price_potion::text, '') AS integer) AS price_potion
     , CAST(NULLIF(rd.price_formula::text, '') AS integer) AS price_formula
     , CAST(NULLIF(rd.complexity::text, '') AS integer) AS complexity
     , NULLIF(trim(rd.time_craft_val), '') AS time_craft_val
     , CASE WHEN rd.time_craft_unit_key IS NOT NULL AND rd.time_craft_unit_key != '' THEN ck_id(rd.time_craft_unit_key) ELSE NULL END AS time_craft_unit_id
     , NULLIF(trim(rd.time_effect_val), '') AS time_effect_val
     , CASE WHEN rd.time_effect_unit_key IS NOT NULL AND rd.time_effect_unit_key != '' THEN ck_id(rd.time_effect_unit_key) ELSE NULL END AS time_effect_unit_id
     , NULLIF(trim(rd.toxicity), '') AS toxicity
     , parse_formula_to_uuid_array(rd.formula_text) AS formula
     , ck_id('witcher_cc.items.recipe.description.'||rd.r_id) AS description_id
  FROM raw_data rd
ON CONFLICT (r_id) DO UPDATE
SET
  dlc_dlc_id = EXCLUDED.dlc_dlc_id,
  name_id = EXCLUDED.name_id,
  group_id = EXCLUDED.group_id,
  availability_id = EXCLUDED.availability_id,
  craft_level_id = EXCLUDED.craft_level_id,
  weight = EXCLUDED.weight,
  minimal_ingredients_cost = EXCLUDED.minimal_ingredients_cost,
  price_potion = EXCLUDED.price_potion,
  price_formula = EXCLUDED.price_formula,
  complexity = EXCLUDED.complexity,
  time_craft_val = EXCLUDED.time_craft_val,
  time_craft_unit_id = EXCLUDED.time_craft_unit_id,
  time_effect_val = EXCLUDED.time_effect_val,
  time_effect_unit_id = EXCLUDED.time_effect_unit_id,
  toxicity = EXCLUDED.toxicity,
  formula = EXCLUDED.formula,
  description_id = EXCLUDED.description_id;

