\echo '001_survey.sql'
-- TRUNCATE TABLE effects;
-- TRUNCATE TABLE answer_options;
-- TRUNCATE TABLE transitions;
-- TRUNCATE TABLE questions;
-- TRUNCATE TABLE i18n_text;
-- TRUNCATE TABLE i18n_keys;
-- TRUNCATE TABLE wcc_dlcs;
-- TRUNCATE TABLE survey_versions;
-- TRUNCATE TABLE surveys;
-- TRUNCATE TABLE rules;

INSERT INTO surveys(su_id, title) VALUES ('witcher_cc', 'Witcher TRPG Character Creator');
INSERT INTO survey_versions(sv_id, su_su_id, is_active, valid_from)
  SELECT 100, su_id, TRUE, now() FROM surveys WHERE su_id='witcher_cc';
-- core DLC/source is mandatory and always available
INSERT INTO wcc_dlcs(dlc_id, su_su_id, title, semver, priority, is_official, name_id)
VALUES (
  'core',
  'witcher_cc',
  'The Witcher TRPG',
  '1.0.0',
  0,
  TRUE,
  ck_id('witcher_cc.items.dlc.name.core')
)
ON CONFLICT (dlc_id) DO UPDATE
SET su_su_id = EXCLUDED.su_su_id,
    title = EXCLUDED.title,
    semver = EXCLUDED.semver,
    priority = EXCLUDED.priority,
    is_official = EXCLUDED.is_official,
    name_id = EXCLUDED.name_id;

-- Иерархия путей (hierarchy paths)
INSERT INTO i18n_text (id, entity, entity_field, lang, text)
SELECT ck_id('witcher_cc.hierarchy.' || v.path) AS id
     , 'hierarchy' AS entity
     , 'path' AS entity_field
     , v.lang
     , v.text
  FROM (VALUES
          ('identity', 'ru', 'Идентичность'),
          ('identity', 'en', 'Identity'),
          ('dlcs', 'ru', 'DLC / Источники'),
          ('dlcs', 'en', 'DLCs / Sources'),
          ('race', 'ru', 'Раса'),
          ('race', 'en', 'Race'),
          ('character_age', 'ru', 'Возраст персонажа'),
          ('character_age', 'en', 'Character age'),
          ('character_name', 'ru', 'Имя персонажа'),
          ('character_name', 'en', 'Character name'),
          ('homeland', 'ru', 'Родина'),
          ('homeland', 'en', 'Homeland'),
          ('homeland_nonhuman', 'ru', 'Родина нелюдя'),
          ('homeland_nonhuman', 'en', 'Non-human homeland'),
          ('family', 'ru', 'Семья'),
          ('family', 'en', 'Family'),
          ('family_threat', 'ru', 'Угроза семье'),
          ('family_threat', 'en', 'Family threat'),
          ('family_fate', 'ru', 'Судьба семьи'),
          ('family_fate', 'en', 'Family fate'),
          ('family_status', 'ru', 'Статус семьи'),
          ('family_status', 'en', 'Family status'),
          ('parents_threat', 'ru', 'Угроза родителям'),
          ('parents_threat', 'en', 'Parents threat'),
          ('parents_fate', 'ru', 'Судьба родителей'),
          ('parents_fate', 'en', 'Parents fate'),
          ('parents_who', 'ru', 'Кто из родителей'),
          ('parents_who', 'en', 'Which parent'),
          ('siblings', 'ru', 'Братья и сестры'),
          ('siblings', 'en', 'Siblings'),
          ('siblings_amount', 'ru', 'Количество'),
          ('siblings_amount', 'en', 'Amount'),
          ('gender', 'ru', 'Пол'),
          ('gender', 'en', 'Gender'),
          ('age', 'ru', 'Возраст'),
          ('age', 'en', 'Age'),
          ('attitude', 'ru', 'Отношение'),
          ('attitude', 'en', 'Attitude'),
          ('personality', 'ru', 'Основная черта характера'),
          ('personality', 'en', 'Personality'),
          ('life_path', 'ru', 'Жизненный путь'),
          ('life_path', 'en', 'Life path'),
          ('friend', 'ru', 'Друг'),
          ('friend', 'en', 'Friend'),
          ('life_events', 'ru', 'Ключевые события в жизни'),
          ('life_events', 'en', 'Life Events'),
          ('life_events_event', 'ru', 'Что произошло'),
          ('life_events_event', 'en', 'What happened'),
          ('life_events_fortune_or_not', 'ru', 'Удача или неудача'),
          ('life_events_fortune_or_not', 'en', 'Fortune or Misfortune'),
          ('life_events_fortune', 'ru', 'Удача'),
          ('life_events_fortune', 'en', 'Fortune'),
          ('life_events_fortune_kind', 'ru', 'Какая именно'),
          ('life_events_fortune_kind', 'en', 'Which one'),
          ('life_events_misfortune', 'ru', 'Неудача'),
          ('life_events_misfortune', 'en', 'Misfortune'),
          ('life_events_misfortune_kind', 'ru', 'Какая именно'),
          ('life_events_misfortune_kind', 'en', 'Which one'),
          ('life_events_misfortune_details', 'ru', 'Уточнение'),
          ('life_events_misfortune_details', 'en', 'Clarification'),
          ('life_events_misfortune_details_2', 'ru', 'Уточнение 2'),
          ('life_events_misfortune_details_2', 'en', 'Clarification 2'),
          ('life_events_misfortune_custom_addiction', 'ru', 'Кастомная зависимость'),
          ('life_events_misfortune_custom_addiction', 'en', 'Custom Addiction'),
          ('life_events_misfortune_custom_curse', 'ru', 'Кастомное проклятие'),
          ('life_events_misfortune_custom_curse', 'en', 'Custom Curse'),
          ('life_events_allies_enemies', 'ru', 'Союзники и враги'),
          ('life_events_allies_enemies', 'en', 'Allies and Enemies'),
          ('life_events_enemy', 'ru', 'Враг'),
          ('life_events_enemy', 'en', 'Enemy'),
          ('life_events_enemy_victim', 'ru', 'Кто потерпевший'),
          ('life_events_enemy_victim', 'en', 'Who was wronged'),
          ('life_events_enemy_gender', 'ru', 'Пол'),
          ('life_events_enemy_gender', 'en', 'Gender'),
          ('life_events_enemy_position', 'ru', 'Кто ваш враг'),
          ('life_events_enemy_position', 'en', 'Who is your enemy'),
          ('life_events_enemy_cause', 'ru', 'Причина вражды'),
          ('life_events_enemy_cause', 'en', 'Cause of conflict'),
          ('life_events_enemy_power_level', 'ru', 'Уровень силы врага'),
          ('life_events_enemy_power_level', 'en', 'Enemy power level'),
          ('life_events_enemy_how_far', 'ru', 'Степень эскалации'),
          ('life_events_enemy_how_far', 'en', 'Escalation level'),
          ('life_events_enemy_power', 'ru', 'Сила врага'),
          ('life_events_enemy_power', 'en', 'Enemy power'),
          ('life_events_ally', 'ru', 'Союзник'),
          ('life_events_ally', 'en', 'Ally'),
          ('life_events_ally_gender', 'ru', 'Пол'),
          ('life_events_ally_gender', 'en', 'Gender'),
          ('life_events_ally_position', 'ru', 'Кто ваш союзник'),
          ('life_events_ally_position', 'en', 'Who is your ally'),
          ('life_events_ally_how_met', 'ru', 'Как познакомились'),
          ('life_events_ally_how_met', 'en', 'How you met'),
          ('life_events_ally_closeness', 'ru', 'Насколько близки'),
          ('life_events_ally_closeness', 'en', 'How close you are'),
          ('life_events_ally_where', 'ru', 'Где он сейчас'),
          ('life_events_ally_where', 'en', 'Where they are now'),
          ('life_events_relationships', 'ru', 'Отношения'),
          ('life_events_relationships', 'en', 'Relationships'),
          ('life_events_relationships_type', 'ru', 'Тип отношений'),
          ('life_events_relationships_type', 'en', 'Relationship type'),
          ('life_events_relationships_details', 'ru', 'История любви'),
          ('life_events_relationships_details', 'en', 'Love story details'),
          ('witcher_age', 'ru', 'Возраст ведьмака'),
          ('witcher_age', 'en', 'Witcher age'),
          ('witcher_graduation_age', 'ru', 'Возраст выхода на Большак'),
          ('witcher_graduation_age', 'en', 'Witcher graduation age'),
          ('witcher', 'ru', 'Ведьмак'),
          ('witcher', 'en', 'Witcher'),
          ('witcher_when', 'ru', 'Когда стал ведьмаком'),
          ('witcher_when', 'en', 'When became a witcher'),
          ('witcher_school', 'ru', 'Школа ведьмака'),
          ('witcher_school', 'en', 'Witcher school'),
          ('witcher_first_trainings', 'ru', 'Первые тренировки'),
          ('witcher_first_trainings', 'en', 'First trainings'),
          ('witcher_trials', 'ru', 'Испытание травами'),
          ('witcher_trials', 'en', 'Trial of the Grasses'),
          ('witcher_most_important_event', 'ru', 'Важнейшее событие'),
          ('witcher_most_important_event', 'en', 'Most important event'),
          ('witcher_child_who', 'ru', 'Пол'),
          ('witcher_child_who', 'en', 'Gender'),
          ('witcher_child_fate', 'ru', 'Судьба'),
          ('witcher_child_fate', 'en', 'Fate'),
          ('witcher_current_situation', 'ru', 'Текущая ситуация'),
          ('witcher_current_situation', 'en', 'Current situation'),
          ('witcher_events_risk', 'ru', 'Рискованность поведения'),
          ('witcher_events_risk', 'en', 'Risk behavior'),
          ('witcher_events_danger', 'ru', 'Опасность'),
          ('witcher_events_danger', 'en', 'Danger'),
          ('witcher_events_is_in_danger', 'ru', 'Какая именно'),
          ('witcher_events_is_in_danger', 'en', 'Which one'),
          ('witcher_events_danger_events', 'ru', 'Событие'),
          ('witcher_events_danger_events', 'en', 'Event'),
          ('witcher_events_danger_events_details', 'ru', 'Детали события'),
          ('witcher_events_danger_events_details', 'en', 'Event details'),
          ('witcher_events_danger_events_details_addiction', 'ru', 'Кастомная зависимость'),
          ('witcher_events_danger_events_details_addiction', 'en', 'Custom addiction'),
          ('witcher_events_danger_events_details_curse', 'ru', 'Кастомное проклятие'),
          ('witcher_events_danger_events_details_curse', 'en', 'Custom curse'),
          ('witcher_events_danger_wounds', 'ru', 'Раны'),
          ('witcher_events_danger_wounds', 'en', 'Wounds'),
          ('witcher_events_danger_enemy', 'ru', 'Враг'),
          ('witcher_events_danger_enemy', 'en', 'Enemy'),
          ('witcher_events_danger_enemy_gender', 'ru', 'Пол'),
          ('witcher_events_danger_enemy_gender', 'en', 'Gender'),
          ('witcher_events_danger_enemy_profession', 'ru', 'Профессия'),
          ('witcher_events_danger_enemy_profession', 'en', 'Profession'),
          ('witcher_events_danger_enemy_reason', 'ru', 'Причина вражды'),
          ('witcher_events_danger_enemy_reason', 'en', 'Cause of conflict'),
          ('witcher_events_danger_enemy_strength', 'ru', 'В чем сила'),
          ('witcher_events_danger_enemy_strength', 'en', 'What is the strength'),
          ('witcher_events_danger_enemy_result', 'ru', 'Степень эскалации'),
          ('witcher_events_danger_enemy_result', 'en', 'Escalation level'),
          ('witcher_events_danger_enemy_is_alive', 'ru', 'Жив ли враг'),
          ('witcher_events_danger_enemy_is_alive', 'en', 'Is enemy alive'),
          ('witcher_events_danger_enemy_death_reason', 'ru', 'Причина смерти'),
          ('witcher_events_danger_enemy_death_reason', 'en', 'Death reason'),
          ('witcher_events', 'ru', 'Исход'),
          ('witcher_events', 'en', 'Outcome'),
          ('witcher_events_benefit', 'ru', 'Выгода'),
          ('witcher_events_benefit', 'en', 'Benefit'),
          ('witcher_events_benefit_type', 'ru', 'Какая именно'),
          ('witcher_events_benefit_type', 'en', 'Which one'),
          ('witcher_events_benefit_details', 'ru', 'Детали выгоды'),
          ('witcher_events_benefit_details', 'en', 'Benefit details'),
          ('witcher_events_benefit_details_2', 'ru', 'Детали выгоды 2'),
          ('witcher_events_benefit_details_2', 'en', 'Benefit details 2'),
          ('witcher_family', 'ru', 'Происхождение ведьмака'),
          ('witcher_family', 'en', 'Witcher''s origin'),
          ('witcher_events_ally', 'ru', 'Союзник'),
          ('witcher_events_ally', 'en', 'Ally'),
          ('witcher_events_ally_gender', 'ru', 'Пол'),
          ('witcher_events_ally_gender', 'en', 'Gender'),
          ('witcher_events_ally_who', 'ru', 'Профессия'),
          ('witcher_events_ally_who', 'en', 'Profession'),
          ('witcher_events_ally_how_met', 'ru', 'Как познакомились'),
          ('witcher_events_ally_how_met', 'en', 'How you met'),
          ('witcher_events_ally_closeness', 'ru', 'Степень близости'),
          ('witcher_events_ally_closeness', 'en', 'Closeness level'),
          ('witcher_events_ally_is_alive', 'ru', 'Жив ли союзник'),
          ('witcher_events_ally_is_alive', 'en', 'Is ally alive'),
          ('witcher_events_ally_death_reason', 'ru', 'Причины смерти'),
          ('witcher_events_ally_death_reason', 'en', 'Death reasons'),
          ('witcher_events_hunt', 'ru', 'Охота'),
          ('witcher_events_hunt', 'en', 'Hunt'),
          ('witcher_events_hunt_prey', 'ru', 'Цель'),
          ('witcher_events_hunt_prey', 'en', 'Prey'),
          ('witcher_events_hunt_location', 'ru', 'Место'),
          ('witcher_events_hunt_location', 'en', 'Location'),
          ('witcher_events_hunt_outcome', 'ru', 'Результат'),
          ('witcher_events_hunt_outcome', 'en', 'Outcome'),
          ('witcher_events_hunt_twist', 'ru', 'Был ли сюжетный поворот'),
          ('witcher_events_hunt_twist', 'en', 'Was there a plot twist'),
          ('witcher_events_hunt_twist_details', 'ru', 'Сюжетный поворот'),
          ('witcher_events_hunt_twist_details', 'en', 'Plot twist'),
          ('style', 'ru', 'Стиль'),
          ('style', 'en', 'Style'),
          ('style_clothing', 'ru', 'Одежда'),
          ('style_clothing', 'en', 'Clothing'),
          ('style_personality', 'ru', 'Характер'),
          ('style_personality', 'en', 'Personality'),
          ('style_hair', 'ru', 'Прическа'),
          ('style_hair', 'en', 'Hair'),
          ('style_affectations', 'ru', 'Украшения'),
          ('style_affectations', 'en', 'Affectations'),
          ('values', 'ru', 'Ценности'),
          ('values', 'en', 'Values'),
          ('values_valued_person', 'ru', 'Кого ценит'),
          ('values_valued_person', 'en', 'Valued person'),
          ('values_value', 'ru', 'Что ценит'),
          ('values_value', 'en', 'Value'),
          ('values_feelings_on_people', 'ru', 'Отношение к людям'),
          ('values_feelings_on_people', 'en', 'Feelings on people'),
          ('profession', 'ru', 'Профессия'),
          ('profession', 'en', 'Profession')
       ) AS v(path, lang, text)
  ON CONFLICT (id, lang) DO NOTHING;